### ISSUE TITLE
Refreshing doesn't work as you would expect.

### ISSUE THREAD

**Issue by cgarvis** [gaearon/flux-react-router-example#14]
Going to http://gaearon.github.io/flux-react-router-example/#/cgarvis redirects to http://gaearon.github.io/flux-react-router-example/#/gaearon

**Comment by gaearon** [comment]
Can you give more exact steps to reproduce the problem?

Do you see this locally or on hosted example? I can't repro.

Maybe you're hitting Enter too fast and input box grabs the focus? I should probably remove autofocus when we're on a user page..

**Comment by cgarvis** [comment]
Search for someone other than yourself and then refresh the page.

**Comment by cgarvis** [comment]
Hmm didn't work on my Mac but works on my phone.  I'll see if I can reproduce tonight on my computerr

**Comment by gaearon** [comment]
Do you have Windows Phone by chance?

**Comment by gaearon** [comment]
Closing this out since I can't reproduce.
Let me know if you find a repro!

Could also be related to https://github.com/rackt/react-router/issues/586 which has been fixed upstream.

**Comment by cridenour** [comment]
I can reproduce.

Click on the original link in this issue, then click in the URL bar and hit enter. (Applies to any "user" page)

**Comment by gaearon** [comment]
Thanks, I see that now!
Fixed by removing autofocus completely.
