### ISSUE TITLE
What are VIEW_ACTION and SERVER_ACTION for?

### ISSUE THREAD

**Issue by AsaAyers** [gaearon/flux-react-router-example#15]
I get that they mark the source of the payload, but I don't see why that would be important information to track. What would you do with them?

**Comment by gaearon** [comment]
In my project I use them mainly for logging (easier to visualize with different sources).
Also I work with a Python API so I actually convert payload to camelCase if it comes from server.

I found no other use for them but didn't want to deviate much from original Flux example.

**Comment by gaearon** [comment]
I'll close this out.
