### ISSUE TITLE
{}

### ISSUE THREAD

**Issue by Vorob-Astronaut** [gaearon/flux-react-router-example#17]
Hi. I have some stupid question for you.
Why you heed `{}` [here](https://github.com/gaearon/flux-react-router-example/blob/master/scripts/components/Explore.js#L5)

**Comment by gaearon** [comment]
It's ES6 [destructuring](http://ariya.ofilabs.com/2013/02/es6-and-destructuring-assignment.html) syntax.
Equivalent to `var Navigation = require('react-router').Navigation`.

Most browsers don't support it yet, but `jsx` can transpile it if you include `harmony` flag, and so can more advanced ES6 transpilers such as `6to5`.

**Comment by Vorob-Astronaut** [comment]
:+1:
