### ISSUE TITLE
Where do you clear stores?

### ISSUE THREAD

**Issue by vesparny** [gaearon/flux-react-router-example#18]
Looking at your code I was wondering where is the point where you clear the store status.
I'll trying to explain myself.

When you are in the first page you submit the form, then in the `UserPage` you call 
```js
UserActionCreators.requestUser(userLogin, ['name', 'avatarUrl']);
```
At this point you will get the UserStore populated.

When you click back button and submit the form with another username, you start over the same process.

I was expecting here to see the `UserStore` still populated with previous data, but if I console.log `{user}` in `UserPage` render method, I see it is initially undefined, then populated again with the new user.

Since Stores are singleton, where do you reset it to undefined.
Probably you don't do it, maybe I see it undefined because is not in bag yet. but I'm missing something here.

Thanks

**Comment by gaearon** [comment]
I don't clear stores.

I think it's generally a bad idea to only hold “current” item in store and clear it when screen changes. Instead, it's much easier to store entities in an `id -> entity` map inside a store, and only query the current one from the component.

**Comment by vesparny** [comment]
thanks for the answer.
I was trying to understand your way of manage stores.
I'm still struggling trying to understand how to organize stores when I have this kind of navigation:

`seach > list > detail`

Do you think keep everything in the same store makes sense?

**Comment by gaearon** [comment]
No, I think you should think about stores kind of like you think about database tables.

I'd have a separate “content” store that maps `id -> entity` and separate “search store” that stores `search term -> [array of ids]`. You'd use them like this:

```js
getStateFromStores(props) {
  var searchTerms = props.params.terms;
  var itemIds = SearchStore.getIds(searchTerms);
  return itemIds.map(ItemStore.getById);
}
```

See also in README: https://github.com/gaearon/flux-react-router-example#how-i-classify-stores

**Comment by vesparny** [comment]
If I think about store like database tables, probably I should have one store for both list and detail since they belong to the same domain ( or table )
Right?

**Comment by gaearon** [comment]
What I meant is that your stores shouldn't contain duplicate data. If you have a list, it needs to be a list of IDs, not a list of objects. Objects have their own store, and all lists refer to them by IDs as if they were “foreign keys”.

I'd keep entities and lists separately because they handle completely different actions. For example, content store only handles updates to individual entities data, and a list only handles pagination, but not data itself. Does this make sense?

**Comment by vesparny** [comment]
Yes it does, I'll think about that.
Thanks

**Comment by gaearon** [comment]
For the sake of completeness, I'll not this is *not* where Flux is going in the future with Relay. In Relay, all data is kept in a single Store (which Relay itself manages). However I think what I suggest a sensible approach until we get our hands on Relay.
