### ISSUE TITLE
can mergeIntoBag function extend to merge two array?

### ISSUE THREAD

**Issue by ChopperLee2011** [gaearon/flux-react-router-example#21]
If my response have some arrays in the entities, the first store init is ok, but when the store changed, `bag[key] = transform(assign({}, bag[key], entities[key]));` will convert the bag[key] which should be array to object;
Cause it is only a example, so just ask.

**Comment by gaearon** [comment]
What's your API response like?

**Comment by ChopperLee2011** [comment]
@gaearon : such as
`{_id: "ChopperLee2011",
name: "chopperlee",
orgs: ["test org1","test org2"],
repos: Array[138]
}`

**Comment by gaearon** [comment]
Why is `bag[key]` an array? It's supposed to be an object. (Like the one you wrote above.) What am I missing?

**Comment by ChopperLee2011** [comment]
key can be 'orgs'', bag[key] is an array :'["test org1","test org2"]', right?

**Comment by gaearon** [comment]
`bag` itself stores entities, not their field. It looks like:

```js
{ 
  'ChopperLee2011': {_id: "ChopperLee2011", name: "chopperlee", orgs: ["test org1","test org2"], repos: Array[138] },
  'SomethingElse': { ... }
}
```

**Comment by ChopperLee2011** [comment]
i am wrong, please close it
