### ISSUE TITLE
connectToStore executing render twice on mount intended?

### ISSUE THREAD

**Issue by broveloper** [gaearon/flux-react-router-example#23]
I had a question regarding the connectToStore component.  It is doing a this.setState on componentDidMount.  This will cause the component to execute render twice when it gets mounted.

Was this intended? What was the reason for running the this.setState on componentDidMount when getInitialState already sets the state?

I'm genuinely curious to know if I'm missing some lifecycle knowledge in the React lifecycle.

**Comment by gaearon** [comment]
This is probably safe to remove. I'm trying to remember an edge case I fixed by this in my own app..

**Comment by broveloper** [comment]
Thanks for responding gaearon!

**Comment by gaearon** [comment]
This is now removed. Instead, subscription is moved from `componentDidMount` to `componentWillMount`.
