### ISSUE TITLE
Upgrade to react + react-router 0.13

### ISSUE THREAD

**Issue by emmenko** [gaearon/flux-react-router-example#24]
Any plan on that? :)

**Comment by gaearon** [comment]
Totally. Haven't gotten around to it yet, but feel free to PR if you'd like!

**Comment by emmenko** [comment]
Cool, will do that if I have some time this WE! ;)

**Comment by emmenko** [comment]
@gaearon I've started migration here https://github.com/emmenko/flux-react-router-example/commits/0.13-migration

Some stuff are not that easy to migrate, especially deprecation of `mixins` and [getting around](https://github.com/emmenko/flux-react-router-example/commit/7ab6327eabacba3216990e56af5145fe1808f918) `context.router`.

I will post here all problems that I will encounter.

**Comment by gaearon** [comment]
Done! Also new in this update:

* a higher-order component and decorators
* less boilerplate in actions thanks to `dispatchAsync` helper
* ditch server action creators!
* `fetch` polyfill instead of `superagent`
