### ISSUE TITLE
duplicate requests

### ISSUE THREAD

**Issue by tadjik1** [gaearon/flux-react-router-example#27]
Hello, thanks for the great flux example.
I'm trying to understand reactjs and flux, and have a question: what happenes if we make 2 async actions? For example request user with login tadjik1 and then we repeat this request. How can we protect our application from this collisions?

**Comment by gaearon** [comment]
I [do this](https://github.com/gaearon/flux-react-router-example/blob/acd4273fc9e94753f5d47913d65e333033d779c3/scripts/actions/RepoActionCreators.js#L21-L22) in action creators:

```js
export function requestStarredReposPage(login, isInitialRequest) {
  // Exit early if already fetching, or if there is nothing to fetch.
  if (StarredReposByUserStore.isExpectingPage(login) ||
      StarredReposByUserStore.isLastPage(login)) {
    return;
  }

  // now we can do the request
  // ...
}
```

The store learns about whether request is in process by listening to the action that gets fired on request start and end.
