### ISSUE TITLE
Example for react-router v1.0.0

### ISSUE THREAD

**Issue by hekike** [gaearon/flux-react-router-example#32]
Hi,

do you plan to do this for `react-router` v1.0.0?
It's on the way: https://github.com/rackt/react-router/tree/v1.0.0-beta1

**Comment by gaearon** [comment]
I'd be happy to (already) accept a PR porting to 1.0 API.
I don't have time to do this but it shouldn't be a lot of work.

**Comment by eriknyk** [comment]
seems there is not a good ducummentation of v1.0.0-beta2 of react router to impl with flux or fluxible :(

**Comment by gaearon** [comment]
I think it's done in master. (I'm happy to accept further patches.)

**Comment by hekike** [comment]
cool thanks!
