### ISSUE TITLE
Debugging with Webstorm ?

### ISSUE THREAD

**Issue by cmrcmr** [gaearon/flux-react-router-example#33]
I'm very new to Nodejs and webpack .. so this might be a silly feature request. Is it possible to have this project to run and debugged under Webstorm ?

**Comment by gaearon** [comment]
Hey! Please see https://github.com/gaearon/react-hot-boilerplate/issues/18 for a discussion.
This project is based on that boilerplate.

**Comment by cmrcmr** [comment]
The discussion conclusion is that webpack support will be available for Webstorm 11. I'm just wondering how do you debug this project without using print statements ? 

I can't find a way to start webpack without packing all the js files into one bundle.js file. Is it possible to tell webpack just to boot up nodejs server without packing it so that Webstorm can debug it ? Please help!

**Comment by gaearon** [comment]
>The discussion conclusion is that webpack support will be available for Webstorm 11. I'm just wondering how do you debug this project without using print statements ?

Not sure I understand your question. I use Chrome DevTools for debugging.

>I can't find a way to start webpack without packing all the js files into one bundle.js file. Is it possible to tell webpack just to boot up nodejs server without packing it so that Webstorm can debug it ? Please help!

That's how Webpack works. It bundles files into one JS file because they're modular. All modern tools work this way.
