### ISSUE TITLE
Port to Redux

### ISSUE THREAD

**Issue by gaearon** [gaearon/flux-react-router-example#38]
I intend to port this example to [Redux](http://github.com/gaearon/redux).

I'm not doing that to promote my library, but because reusable store utilities (like pagination) are _way_ easier to implement as pure functions. What I have right now in [`PaginatedStoreUtils`](https://github.com/gaearon/flux-react-router-example/blob/master/scripts/utils/PaginatedStoreUtils.js) is a mess, and will be much more sensible with Redux approach.

However, I understand that not everybody will be happy with this change, as [Redux is not _exactly_ Flux](https://medium.com/@dan_abramov/the-evolution-of-flux-frameworks-6c16ad26bb31). I think it solves the same problems better than Flux, but that's my opinion and some may not share it.

Therefore I ask what you think:

* Should I rename the repository to reflect that it's a Redux example now?
* Should I keep the old vanilla Flux code in a branch?

To clarify again:

* I intend to keep it minimal, just like the current repo, and handle the same cases: pagination, “load more”, spinners.
* The “content stores” / “list stores” distinction will be even clearer with reusable reducers.
* This is not an artificial effort to port for the sake of porting. The code will be clearer after porting to Redux, and the idioms currently used by the code will be more apparent and natural.

Thoughts?

**Comment by felipeleusin** [comment]
Imho rename and kee pthe flux in an old branch and keep a link in the readme.... Between redux and react-router 1.0 there is going to be A LOT of changes. Also, thanks for all the work you've been doing with reflux lately!

**Comment by fibric** [comment]
like @felipeleusin has said it, rename it and keep the old version. maybe as branch or maybe even only as link to current revision.

**Comment by davidwatkins73** [comment]
agree with @felipeleusin. V. interested in seeing this port.

**Comment by i4got10** [comment]
It might be better to make a new repository redux-react-router-example

**Comment by idolize** [comment]
Awesome, can't wait for this!

**Comment by gaearon** [comment]
The port will be part of the official Redux repo.
PR: https://github.com/gaearon/redux/pull/460

**Comment by gaearon** [comment]
The Redux port is here: https://github.com/rackt/redux/tree/master/examples/real-world
