### ISSUE TITLE
Handle server-side rendering

### ISSUE THREAD

**Issue by martintietz** [gaearon/flux-react-router-example#8]
Great work on putting this together! Just one question: Do you have an idea on how you would integrate server-side rendering into your app?

**Comment by gaearon** [comment]
For server side rendering, I'd rather use [Flummox](https://github.com/acdlite/flummox). This repo is purposefully stripped down to show the basic concepts, so I'm not shoehorning server rendering in it. If you're comfortable with Flux, just go ahead and check out Flummox's [progressive docs website that renders on server first](https://github.com/acdlite/flummox/tree/master/docs).
